#!/bin/bash

if [[ -n ${1} && ${1} == '--update' ]]; then
  curl -L "https://github.com/bddenhartog/bagger/raw/master/bagger" > $(which bagger)
  exit 0
fi

NAME=$1
TARGET=$2
IGNOREFILE=".baggerignore"
LOC=`which bagger`

if [[ -z ${NAME} || -z ${TARGET} ]]; then
  echo "error:"
  echo "  - missing required option(s)"
  echo
  bagger --help !
  exit 0
elif [[ ${NAME} == "?" || ${NAME} == "--help" ]]; then
  echo "bagger:"
  echo "  - usage:"
  echo "    ${LOC} NAME TARGET"
  echo
  echo "  - to update:"
  echo "    ${LOC} --update"
  exit 0
else
  if [[ ${NAME} != *".zip" ]]; then
    NAME="${NAME}.zip"
  fi
  
  echo "bagger:"
  echo "  - bagging directory: ${TARGET}..."
  
  pushd ${TARGET}
  if [[ -f ${IGNOREFILE} ]]; then
    zip -r ${NAME} ./* -x@${IGNOREFILE}
  else
    zip -r ${NAME} ./*
  fi
  popd

  echo "  done."
fi
