#!/bin/bash

if [[ -n ${1} && ${1} == '--update' ]]; then
  curl -L "https://github.com/bddenhartog/bagger/raw/master/bagger" > $(which bagger)
  exit 0
fi

NAME=$1
TARGET=$2
IGNOREFILE=".baggerignore"

echo "bagger:"
if [[ -z ${NAME} || -z ${TARGET} ]]; then
  echo "  - missing required option(s)"
  echo "  - usage:"
  echo "    $ bagger NAME TARGET"
  echo
  echo "  - to update:"
  echo "    $ bagger --update"
  exit 0
fi

if [[ ${NAME} != *".zip" ]]; then
  NAME="${NAME}.zip"
fi

if [[ -n ${NAME} && -n ${TARGET} ]]; then
  echo "  - bagging directory: ${TARGET}..."
  
  pushd ${TARGET}
  if [[ -f ${IGNOREFILE} ]]; then
    zip -r ${NAME} ./* -x@${IGNOREFILE}
  else
    zip -r ${NAME} ./*
  fi
  popd

  echo "  done."
fi

echo && echo
